### ISSUE TITLE
design CLDR distribution mechanism

### ISSUE THREAD

**Issue by mrhota** [ogham/rust-locale#10]
I mentioned this in #9. We don't have to create something novel here; other projects have blazed this trail before. Perhaps take a look at jquery globalize and python babel. They are linked on the [References](https://github.com/rust-locale/rust-locale/wiki/References) wiki page.

I mentioned cargo's [features] sections to allow users to specify which data they need as part of the rust-locale distribution. Maybe they'll specify language tags? That seems like an obvious choice, but maybe there's something nicer, easier, or more specific?

Or maybe we can provide "bite-sized" chunks of CLDR data, and deliver data for multiple locales under one cargo [feature]. Like "europe" would deliver all locales for the European cultures, "america" for north and south america and the Carribean, etc. I actually don't like this idea now that I've mentioned it.

Would we need to have a CLDR crate? How else would we deliver appropriate data?

**Comment by jan-hudec** [comment]
For $work, what I do is that I create special "messages" like "digits|01234567890", "plus_sign|+", "locale_name|English (USA)" etc. (`|` is actually "\036"-or-whatever-gettext-uses-as-context-separator), add them in the `.pot`, translate them from CLDR using a python script and compile them in the `.mo`. And simply get everything from the messages.

So I think we should eventually have two methods:
- bundled, where everything would live in one big, compiled-in, static hash.
- in translation, with the tool extracting translatable strings able to add them to the .po files and inject the CLDR translations (the tool itself can be built bundled, so it will have the values handy). For limited devices where the user does not want to bundle it.

**Comment by mrhota** [comment]
That's an interesting approach.

> - bundled, where everything would live in one big, compiled-in, static hash.

By "everything" do you mean all of CLDR data in one data structure?

python-babel appears to pickle/serialize CLDR data into lots of files. One file for en-US currency names, one for es-MX currencies, same for datetimes, language names, and all the rest. Is this what you meant by your first bullet point? If not, we should add this method to the list.

The script that python-babel uses is called at distribution (installation?) time. It downloads a given CLDR distro, parses the data and pickles it to disk. BTW, their issue tracker has a nice issue about the design and its (lack of) extensibility: python-babel/babel#344

**Comment by jan-hudec** [comment]
By bundled I meant the way ICU does it. All data, for all supported locales, go in the shared library.

**Comment by jan-hudec** [comment]
Hm, interesting.

Basically by bundled I mean similar approach to ICU. They just pack everything into one big binary file and potentially link it into the shared library itself.

I have rejected it for $work because the pack is [really huge (~29MiB)¹](http://apps.icu-project.org/datacustom/). However, for desktop it shouldn't be a problem and we don't want to include everything they do (especially not the charset conversion tables that take up third of the bundle).

---

¹ By the way, my `/usr/lib/locale/locale-archive` with all locales has 114MiB! I am not sure how efficiently packed it is though; probably not much.

**Comment by mrhota** [comment]
Yeah, avoiding a _full CLDR install_ would be helpful.

I think we can leverage cargo's [features] like the examples below, but I'm not super familiar with it, so it might not be suitable. If you can think of a better mechanism for letting users select specific locale data, we should list it here (or the wiki).

`cargo install rust-locale --features "en_US vi_VN zh_CN"`
or
`cargo install rust-locale --features "full-cldr"`
etc.

I think that's really sexy (if perhaps tedious if they need lots of individual locales). It's so easy from the user's perspective.

We'd have to deal with `cfg` attributes to handle the features. That actually doesn't sound fun, since the list of "official" language tags can vary over time. And I don't think we can "parameterize" attributes like that.

`#[cfg(feature = foo)]` where foo is the list that was passed on the command line through `rustc --cfg feature=...`. As opposed to `#[cfg(feature="foo")]` for a particular item from the command line arguments. I'm pretty sure that's not a thing.

**Comment by jan-hudec** [comment]
> cargo install rust-locale --features "en_US vi_VN zh_CN"

That would be insane; there is well over hundred of those.

I would just have a bundled CLDR (a couple of MiB, in a shared library no problem for desktop or newer mobile) and the keys that the application would inject in its `.mo` files using provided utility for those applications that are intended to run in severely restricted environments.

Also,

> cargo install

Remember, `locale` is a library. It is installed implicitly by cargo as part of installing some application. User won't get to select the features.

**Comment by mrhota** [comment]
> That would be insane;

Well, yeah. :smiley: But imagine I'm a dev at Foo, Inc. and our main product, FooForYou, only supports American English, Vietnamese, and Mandarin. Then selecting "features" like that would be reasonable since those three are all I care about. As FooForYou supports more and more locales, adding each individual tag becomes unreasonable, and you'd want to just say "give me everything CLDR supports" or something more convenient.

> Remember, locale is a library.

You're right, the CLI command is wrong. I should have written the example below. The consumers of `rust-locale` would select the "features" in their `Cargo.toml`:

```
[dependencies.rust-locale]
version = "1.0.0"
default-features = false # do not include the default features, and optionally
                         # cherry-pick individual features
features = ["en_US", "vi_VN"]
```

Anyway, yes, writing every language tag is silly. More thought here is required. I'm not married to this method of data delivery. I like it as a starting point for discussion, though.

**Comment by jan-hudec** [comment]
> But imagine I'm a dev at Foo, Inc. and our main product, FooForYou, only supports American English, Vietnamese, and Mandarin.

That's what the `.mo` approach is for. You just request `features = []` and ask the `rxgettext` tool to add the CLDR data to your translation catalogs.

**Comment by mrhota** [comment]
OK, for the full-CLDR-install case, I understand it to be something like this:
1. User installs rust-locale, indicating (somehow) they want all CLDR data.
2. CLDR data files are installed so rust-locale can use them.
3. User constructs a `Locale` object, `foo`, and rust-locale does The Right Thing (opening files? mmap-ing files?) so the CLDR data files/data are accessible for locale sensitive services like date formatting.
4. User constructs message formatter for locale `foo` to load the user's appropriate message catalogs. rust-locale does The Right Thing to load the catalogs so the user can format localized messages. If user wanted to print a localized message which also includes a date, they'd use a date formatter _and_ the message formatter.

Is that at least approximately right?

To be honest my experience of localized message catalogs is restricted to unsophisticated usage of java properties files. So I'm not even sure about 4, above.

I haven't fully understood the `.mo` approach you brought up (partly because I'm not familiar with `gettext`). Can you outline it in a bit more detail? (Did you mean `xgettext` instead of `rxgettext`, or is `rxgettext` the Ruby or hypothetical rust version of `xgettext`?)

**Comment by jan-hudec** [comment]
The `.mo` is very similar to the Java properties. It is simply an external hash.

The specific thing with `.mo` files is, that the keys are strictly either the original string, or a pair of context and original string. This has two advantages:
- it automatically falls back to the primary language (usually English), which makes missing translation bugs less severe and
- it makes it easy to track changes as if the original changes, it will simply come up as new key missing translation.

The context is for distinguishing short labels, e.g. "file action" "Open" from "port state" "Open"; the former is a verb and the later is a noun and in most languages that will be different words.

The translation will be done by message translator. Message formatter will be a layer on top of the rest that will tie everything together.

And yes, by `rxgettext` I mean a rust-specific version of `xgettext`, the tool to extract the strings that need translation.

**Comment by jan-hudec** [comment]
Regarding storing the locale data in `.mo` files, remember, that in GNU LibC, _all_ the locale data are read (even internally) via `nl_langinfo`, which returns a string (the bytes and byte arrays can be encoded in strings easily and the wide variants are just alternates we don't need). So instead of `nl_langinfo` we just do a `cgettext`.

E.g. numeric formatting needs digits, + and - sign, decimal separator, group separator and group sizes. So we get them as

```
cgettext("numeric/digits", "0123456789")
cgettext("numeric/plus", "+")
cgettext("numeric/minus", "-")
cgettext("numeric/group-separator", ",")
cgettext("numeric/decimal-separator", ".")
cgettext("numeric/grouping", "33")
```

it is actually rather inefficient, because each `.mo` file must contain the keys including the contexts. However if you just need some attributes (e.g. no need to store monetary formats if the application does not use them) for only few supported languages, it is much smaller than bundling everything.

Note that we could abbreviate the context and we can combine the keys to make it more efficient. The values will always be shorted than the keys though.

**Comment by jan-hudec** [comment]
Ok, we should start somewhere. For start we need two things:
- Something that will take a `LanguageTag` and finds most suitable definition from a set. I've already defined accessors for the subtags in https://github.com/rust-locale/rust-locale/commit/9bb840770f83a35d4bf12a6f64c765a25478fb29, but perhaps we'll see something slightly different will be needed. I also wrapped them in `locale` in https://github.com/rust-locale/rust-locale/commit/c16fd7de32fdf4552822de4158f8b64139ed0df2, but if the CLDR library is going to be separate, it should only depend on the `locale_core`, because the `locale` crate will depend on it and we can't have circular dependencies.
- Something that will go through the CLDR definition for each language and from specified nodes will generate simple key-value pairs. Strings should do for start.

The first (and simplest) elements we are going to process are the `/numbers/symbols/decimal`, `/numbers/symbols/group`, `/numbers/decimalFormats/decimalFormatLength/decimalFormat/pattern[not(@type)]` and such. I think XSLT would work. There does not seem to be any in Rust yet, but this is offline and does not have to be in Rust.

Since I don't think cargo has much in a way of support for installing resource files, I think it would be best to generate Rust code with all the tables that we would just include in the upload to crates.io. The [phf](https://crates.io/crates/phf) crate seems like a decent option to me.

@mrhota, would you look at it and perhaps start prototyping some generator? Simple and limited for start; we should have something working first and polish it later.

**Comment by mrhota** [comment]
I'll write a python script to begin with. I will want to move to a pure rust generator later so we don't have extraneous, implicit dependencies on other systems.

Python should be fine for a start.

**Comment by jan-hudec** [comment]
Great.

I think python would do even forever, since it is just a development dependency. And in this case even for development of `locale` itself and not the crates that use it, though we will, at least at first, certainly have development python dependencies for them too—I don't intend to rewrite [translate toolkit](http://toolkit.translatehouse.org/) (nor [gettext](https://www.gnu.org/software/gettext/gettext.html)) any time soon.

**Comment by mrhota** [comment]
my computer has been out of commission for a while, but it's back now. I have adapted the CLDR fetch+parse scripts from the Python Babel project. They use the Python pickle serialization format, which I'm not happy with. It seems like the serde-pickle plugin is immature at this point.

I'll push soon

**Comment by jan-hudec** [comment]
Thank you.

> Python pickle serialization format, which I'm not happy with.

I am not happy with it either.
- The nested maps structure is mostly fine in dynamically typed language like python, but in Rust it would require a recursive type with variants. A flat map would be simpler.
- The final format should be possible to [`include_bytes!`](https://doc.rust-lang.org/std/macro.include_bytes!.html) or [memmap](https://crates.io/crates/memmap) and access it without (much) additional allocation.

I was considering [cdb format](https://cr.yp.to/cdb.html), but the [cdb crate](https://crates.io/crates/cdb) uses the unmaintained mmap crate, which does not work on Windows, and the [tinycdb crate](https://crates.io/crates/tinycdb) requires a C library. Another option would be to use the [phf crate](https://crates.io/crates/phf), with the disadvantage that it has to be linked in and can't be read from file (it could be read from shared library, but that would still be platform-dependent).

Also we actually don't need one flat layer, but two — first by language tag and second by item. And disadvantage of the [cdb format](https://cr.yp.to/cdb.html) (or mo format, for that matter; they are actually quite similar) is that the keys would have to be repeated for each language.

And maybe we will need more layers in the end anyway. In some places we will need to enumerate available items. E.g. available skeletons for date+time.

Either way we are going to have to shave some yaks. But we can start with something less efficient and switch to something more efficient later.

**Comment by jan-hudec** [comment]
> It seems like the serde-pickle plugin is immature at this point.

And I don't think `serde-pickle` is going to read the Babel serialized locale data anyway. It would have to read into something like:

```
enum Node {
    Value(String),
    Dict(Box<HashMap<String, Node>>),
}
```

and I am not sure it would know, or can be explained, how.

**Comment by jan-hudec** [comment]
Looking at [serde](https://github.com/serde-rs/serde), a good format for use at the moment might be [msgpack](http://msgpack.org/). It has [python implementation](https://pypi.python.org/pypi/msgpack-python/) and it has [rust implementation](https://github.com/3Hren/msgpack-rust) (the [original](https://github.com/mneumann/rust-msgpack) seems unmaintained) including serde support. And it is most compact of the readily supported options.

**Comment by mrhota** [comment]
msgpack looks good to me

**Comment by jan-hudec** [comment]
Great. Can you push something somewhere, even if it is incomplete so we can talk about interface?

**Comment by mrhota** [comment]
btw, I'm not dead! I'm experimenting with some different delivery methods. msgpack no longer seems like the right choice. Dumb JSON + (gzip|bzip2|xz) would give us everything we need (right now) for data retrieval flexibility, plus it will produce smaller files.

I should have a PR later this week.

**Comment by jan-hudec** [comment]
Ok.
If compression gives better results — and it makes sense, the strings take as much in msgpack as they do in json — go ahead. Just don't spend too much time perfecting it. We should have some prototype first and can perfect it later.

**Comment by mrhota** [comment]
@jan-hudec  see here for an "alpha" version: https://github.com/mrhota/cldr-rs

I published as a crate, too: https://crates.io/crates/cldr

The build script clones all CLDR repos, compresses the JSON files using bzip2, and puts them in the output dir, available for the CLDR lib to read. I haven't really started the lib part of the crate.

**Comment by jan-hudec** [comment]
@mrhota , how is that supposed to be used? As it is it **can't** be used as a a dependency of `locale` because:
- CLDR schema is evolving too. Does the json extract provide sufficient stability guarantee that we can blindly fetch the latest version when, for whatever reason, rebuilding old version of `locale`?
- The build script currently requires nightly compiler. `locale` is supposed to work with stable.
- Distribution folks are gonna hate us if we insist on downloading anything as part of build. This can be fixed by first checking whether suitable local copy was already made and downloading only if not.

And then, the whole thing is _huge_. It has 21 MiB apparent size and 41 MiB disk usage. In contrast, ICU has, on my system 25 MiB, but that includes 9.1 MiB of charset conversion data we don't have. And even then, we are going to use far from all of it.

Last but not least, cargo still lacks mechanism for installing data files. So the only thing that would actually work for crates wanting to be installed via `cargo install` is if we embed the data in the binary (though we clearly eventually want that to be optional).

**Comment by mrhota** [comment]
@jan-hudec it isn't supposed to be used yet, which I hoped would be clear from the README in the repo.

> we can blindly fetch the latest version

Notice that the version of my CLDR crate is 29.0.0-alpha. The build script checks out the tag matching the CLDR crate's version; not `master`.

> The build script currently requires nightly compiler. locale is supposed to work with stable.

I don't remember ever discussing this constraint. Anyway, we don't have much of a `locale` library to speak of yet. I can easily change to stable before releasing a non-alpha version. I want to lay down broad strokes here and get something going even if it requires nightly.

> checking whether suitable local copy was already made

I'm going to move forward with fleshing out structs around CLDR data so this becomes a real library. You can make a PR (or file an issue) to help make the build script more polite and intelligent. Saving 10 - 20 MiB of space is of secondary importance at this early stage.

> the only thing that would actually work

I don't think this is a problem. You wouldn't `cargo install cldr` because it doesn't have bin targets. Meanwhile, depending on `cldr` in a `Cargo.toml` file will allow the data to be written into `OUT_DIR` where the `cldr` lib has access to them without them being embedded in the libs. I did some cursory checks and it seemed to work fine. Did I understand you correctly?

**Comment by mrhota** [comment]
leave further comments about CLDR crate on that project's issue tracker

**Comment by jan-hudec** [comment]
Ok. Here is muuuuch simpler solution. There already *is* a library that bundles CLDR data and provides interfaces to them. It is also developed with lockstep with them. The [ICU](http://site.icu-project.org/).

So the primary CLDR distribution mechanism will be simply using ICU as a backend. For everything. I don't like how some bits of it are done, but it's best to get things working first and pretty later.

:white_check_mark: designed.
