### ISSUE TITLE
locale bindings should live in rust-lang/libc

### ISSUE THREAD

**Issue by mrhota** [ogham/rust-locale#8]
I'm not sure what the approach should be here. As I see it, we have two options:
1. We enhance `libc` or some other appropriate lib to include bindings to system locale services.
2. We provide our own bindings to supported systems' locale services.

Have I forgotten anything?

I've got a question/issue started over on libc's repo: rust-lang/libc#242

**Comment by jan-hudec** [comment]
The bindings for GNU Libc `locale_t` struct and `nl_langinfo_l` function are already there! Look at the code (the `linux` submodule). However:
- It will need proper conditioning on target, since:
  - OSX also has those functions, but the set of supported items is different (GNU LibC has _a lot_ of extensions).
  - Musl also has those functions, but the set of supported items is different, and very small in this case; basically only those few [defined in POSIX](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/langinfo.h.html).
  - Currently the code is `#[cfg(linux)]`, which will make it compile for `*-unknown-linux-musl` and break horribly there because of the mismatched constants. I am not sure whether it will make it compile for `*-linux-androideabi`, but it won't work there either way.
- Windows don't have `nl_langinfo` and don't support most features via LibC, so we'll need bindings to `winnls.h` functions there. They already exist in [`winapi` (`kernel32-sys`)](https://github.com/retep998/winapi-rs).
- Android declares the functions, but does not seem to have any data for them, so they won't be much use there anyway.

The bindings are public in the 0.2 version, but I will make them private in the next one. They can be factored out to `libc` if somebody else wants them (they seem to be [in scope](https://github.com/rust-lang/rfcs/blob/master/text/1291-promote-libc.md#scope-of-libc)). I don't think anybody should though, because their use is highly platform-specific.

However, they **don't have anything to do with system _settings_ anyway**. To access system locale **settings**, all we need on Unix is (in _increasing_ order of precedence) the `LANGUAGE`, `LANG`, `LC_*` and `LC_ALL` environment variables. On Windows we'll need the functions from winnls, plus the LCID table and on Android we will probably need a call through to Java (I know where to look, but I did not yet).

**Comment by jan-hudec** [comment]
By the way, @mrhota, do you have any idea what is the distinction between user locale and user _UI_ locale on Windows?

**Comment by mrhota** [comment]
I have a PR for libc at rust-lang/libc#244

I fixed the title of this issue.

Bindings for i18n-related, platform-specific functions and types should live in libc. That's its whole purpose. It also takes care of conditionally including/excluding relevant things from given targets. There's no need for this project to duplicate that effort.

**Comment by mrhota** [comment]
No, I know next to nothing about Windows. Is that question relevant to the issue here; bindings to system library functions and types?

**Comment by jan-hudec** [comment]
> Bindings for i18n-related, platform-specific functions and types should live in libc.

They probably should. But I don't think the interpretation of the returned value as string, byte, byte array or string array depending on the parameter passed is in libc scope and that is the only substantial part of that binding. And then we'll have platform dependence here anyway, because different functions must be used on GNU LibC, other POSIX, WinAPI and Android. Having the five functions, one struct and a bunch of constants exported by libc won't make all that much difference.

> Is that question relevant to the issue here

After the retitling, no, it is not. Those functions are bound in `winapi` all right, the only question there is when and how to use them.

**Comment by mrhota** [comment]
> I don't think the interpretation of the returned value as string, byte, byte array or string array depending on the parameter passed is in libc scope and that is the only substantial part of that binding.

Can you be more explicit?

**Comment by jan-hudec** [comment]
The stuff in [src/linux/langinfo.rs](https://github.com/rust-locale/rust-locale/blob/a524ccbfa282899d1cb2691385adfec74a1b68a8/src/linux/langinfo.rs).

Of course if it is going to be internal implementation detail, we can probably drop the enums and just call the `decode_*` functions explicitly in the facet implementation. But I don't think those are in scope of `libc` and that is where the largest potential for error lies.

**Comment by mrhota** [comment]
`nl_langinfo{_l}` returns `*mut ::c_char`, plain and simple. There should be no need to interpret returned pointers as strings, byte arrays, or string arrays.

**Comment by mrhota** [comment]
BTW, I put together bindings and type defs for all non-windows platforms that libc supports. This gives access to stuff in locale.h, xlocale.h, and langinfo.h.

**Comment by mrhota** [comment]
@jan-hudec I see the commit message for your discussion about `nl_langinfo_l`, but I'm still trying to find documentation about that function's return values needing to be interpreted in different ways. The documentation at [Open Group specs](http://pubs.opengroup.org/onlinepubs/9699919799/functions/nl_langinfo.html#) says the return value is a string. The GNU C Library Manual also talks about `nl_langinfo`, but it says nothing about this "polymorphic" return type you mentioned.

**Comment by jan-hudec** [comment]
> `nl_langinfo{_l}` returns `*mut ::c_char`, plain and simple.

It does. But you can't work with that type in Rust directly, so the second layer is needed to convert it into a native Rust something. And that is done differently depending on the constant used.

> but I'm still trying to find documentation about that function's return values needing to be interpreted in different ways.

Well, there are some items, most obviously `GROUPING` and `MON_GROUPING`, that don't have obvious representation as string. So I checked. And `nl_langinfo(GROUPING)` gives a string starting with `"\003\003\377"` and continuing with some more garbage. This is a byte array and it is terminated with -1 rather than 0 as strings are.

Then I just Used The Source. Specifically, [locale/categories.def](https://sourceware.org/git/?p=glibc.git;a=blob;f=locale/categories.def;h=d8a3ab8127d542b528f9d37c41a062133786455a;hb=master) has the complete list of items with returned types, and if you hunt down definition of the macro, you can find what the definitions mean.

> The documentation at Open Group specs says the return value is a string.

The Open Group spec defines only a [few of the items](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/langinfo.h.html) and none of the ones it does define seem to return anything else than string. So it does not need to say that.

In particular, it does _not_ specify the `GROUPING` and `MON_GROUPING` items. That information has to be obtained via [localeconv](http://pubs.opengroup.org/onlinepubs/9699919799/functions/localeconv.html) instead. I wanted to avoid that as it does not have an `_l` variant and I did _not_ want to set the locale for C library to avoid breaking the other Rust core code that might not expect it to be set. Though we should be able to `uselocale` (which is thread-local) just for getting the information and then just reset it to the previous value that `uselocale` returned.

On a different note, GNU LibC prefixes the item names that are specific to it with `_NL_`, but `GROUPING` does not have that prefix and does not even have `_` prefix which suggests it does come from some standard. I don't know which one though.

> BTW, I put together bindings and type defs for all non-windows platforms that libc supports.

[Here?](https://github.com/rust-lang/libc/pull/248)

**Comment by mrhota** [comment]
For the purposes of this project, we don't care about these details. Who cares how f***ed up GNU extensions are? I have provided bindings to functions and types in rust-lang/libc. If users want to torture themselves using libc crap, they can have at it on their own time.

We should not wrap C's crappy API. We should call `setlocale` once to figure out current locale when rust-locale loads, and (probably) never again call a libc function. This isn't C++. We can divorce ourselves from libc. We don't even have to use C++'s (terrible) jargon. The world has moved on since the 80s.

If we want to provide a _**rust-locale**_ API to the platform's locale _data_, we can talk about that in a separate issue.

If you _really_ want to wrap platform locale API's, you're going to have a bad time. `langinfo.rs` is evidence enough. You can put it on the roadmap, if you want, but I think we have bigger fish to fry.

**Comment by jan-hudec** [comment]
No, we don't.

However,

> Who cares how f***ed up GNU extensions are?

They are the sanest out there. They actually allow getting all the values without having to set global state.

> We should call `setlocale` once

No, we should **never** call `setlocale`. _IF_ we want to use libc as backed, we will be forced to call `uselocale`. I wanted to avoid that too, but `strcoll` and `strxfrm` don't seem to have variant taking `locale_t` and on non-GNU systems `localeconv` is needed which does not either.

Now I would like to ignore the libc altogether and just extract the data from CLDR and bundle them, but I am somewhat afraid of the collation algorithm is. It looked pretty convoluted to me.
